spring:
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
        
    datasource:
        //driverClassName: org.h2.Driver
        driverClassName: org.postgresql.Driver
        //url: jdbc:h2:file:C:\environment\tmp\testdb
        url: jdbc:postgresql://localhost:5432/student
        username: postgres
        password: postgres

security.basic.enabled: false